// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for ios - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDiAQN_2l_YicQJe2jUj0S6IwYr2Um0IRI',
    appId: '1:238326040602:web:4f28c3ca6d72e14fab69a3',
    messagingSenderId: '238326040602',
    projectId: 'auto-matic-f20e7',
    authDomain: 'auto-matic-f20e7.firebaseapp.com',
    databaseURL: 'https://auto-matic-f20e7-default-rtdb.firebaseio.com',
    storageBucket: 'auto-matic-f20e7.appspot.com',
    measurementId: 'G-CVG5YE294X',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAoFWbwm9kNgIDwPkijssDLSZXEdVKUfLE',
    appId: '1:238326040602:android:a9c513a5ea93d011ab69a3',
    messagingSenderId: '238326040602',
    projectId: 'auto-matic-f20e7',
    databaseURL: 'https://auto-matic-f20e7-default-rtdb.firebaseio.com',
    storageBucket: 'auto-matic-f20e7.appspot.com',
  );

}